# Generated by Django 2.2.15 on 2020-11-10 18:06

import base.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'cache',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_name', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'control',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=255)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
                ('platform', models.CharField(blank=True, default='', max_length=255)),
                ('ipv4_prefix', models.CharField(blank=True, default='', max_length=18)),
                ('ipv6_prefix', models.CharField(blank=True, default='', max_length=43)),
                ('enabled', models.BooleanField(default=False)),
                ('alarm_timeperiod', models.CharField(blank=True, default='', max_length=255)),
                ('alarm_destination', models.CharField(blank=True, default='', max_length=255)),
                ('alarm_interfaces', models.BooleanField(default=False)),
                ('connection_method', models.CharField(blank=True, default='', max_length=255)),
                ('monitor_grafana', models.BooleanField(default=False)),
                ('monitor_icinga', models.BooleanField(default=False)),
                ('monitor_librenms', models.BooleanField(default=False)),
                ('backup_oxidized', models.BooleanField(default=False)),
                ('field_src', models.CharField(blank=True, db_column='_src', default='', max_length=10)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('ipv4_prefix', models.CharField(blank=True, default='', max_length=15)),
                ('ipv6_prefix', models.CharField(blank=True, default='', max_length=39)),
                ('enabled', models.BooleanField(default=False)),
                ('field_src', models.CharField(blank=True, db_column='_src', default='', max_length=10)),
                ('device', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='base.Device')),
            ],
            options={
                'db_table': 'interface',
            },
        ),
        migrations.CreateModel(
            name='Log_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
#                ('serialid', base.models.SerialField(default=base.models.get_next_log_serialid_seq, editable=False, unique=True)),
                ('facility', models.IntegerField(null=True)),
                ('severity', models.IntegerField(null=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('appname', models.CharField(blank=True, default='', max_length=48)),
                ('procid', models.CharField(blank=True, default='', max_length=128)),
                ('msgid', models.TextField(blank=True, default='', max_length=64)),
                ('msg', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('field_src', models.CharField(blank=True, db_column='_src', default='', max_length=10)),
                ('device', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='base.Device')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, default='', max_length=255)),
                ('field_src', models.CharField(blank=True, db_column='_src', default='', max_length=10)),
                ('device', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='base.Device')),
            ],
            options={
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='InterfaceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, default='', max_length=255)),
                ('field_src', models.CharField(blank=True, db_column='_src', default='', max_length=10)),
                ('interface', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='base.Interface')),
            ],
            options={
                'db_table': 'interfacetag',
            },
        ),
    ]
