# Generated by Django 2.2.15 on 2020-11-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='ipv4_prefix',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='interface',
            name='ipv6_prefix',
            field=models.CharField(blank=True, default='', max_length=43),
        ),
    ]
