# Generated by Django 2.2.15 on 2020-11-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
