# Generated by Django 2.2.15 on 2020-11-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cache_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
