# Generated by Django 2.2.24 on 2021-10-17 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_keyval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyVal',
        ),
    ]
